name: Snaplet Restore
on:
    schedule:
      - cron: '* * * * 5' # At 04:00 on every day-of-week from Monday through Friday.
    workflow_dispatch:
jobs:
  snaplet-restore-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Snaplet CLI
        run: curl -sL https://app.snaplet.dev/get-cli/ | bash
      - name: Restore Snapshot
        run: snaplet snapshot restore -y --latest
        env:
          SNAPLET_DATABASE_URL: ${{ secrets.SNAPLET_DATA_TARGET_DB_URL }}
          SNAPLET_ACCESS_TOKEN: ${{ secrets.SNAPLET_ACCESS_TOKEN }}
          SNAPLET_PROJECT_ID: ${{ secrets.SNAPLET_ID }}
